name: "React to Surge"

# Only push to surge if in app folder
on:
  push:
    paths:
      - dev/client/**
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Building React Project
        run: |
          cd ./dev/client/my-app
          npm install
          npm run build
        shell: bash
        
      - name: Deploy to filtex.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'filtex.surge.sh'
          project: './dev/client/my-app/build'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
